PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE CASE_INFO(
ID INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
FILE_NAME TEXT NOT NULL,
AUTHOR TEXT NOT NULL,
CREATE_DATE TEXT NOT NULL,
LAST_UPDATE_BY TEXT NOT NULL,
LAST_UPDATE_TIME);
CREATE TABLE COMMIT_TRACE (
ID INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, 
COMMIT_ID TEXT NOT NULL
);
DELETE FROM sqlite_sequence;
COMMIT;
