db_path='./app.db'
git_repo='./PLT-User'
case_folder='./PLT-User/src/com/successfactors/test/qray/cases/plt/usermanagement'
svn_username='jzheng'
svn_pwd='niP8Sf'
svn_addr='https://svn.successfactors.com/repos/V4/branches/offshore/t2/qraywriter'
svn_src='C:/Users/i306454/qray repo/src/com/successfactors/test/qray/cases'