db_path='./app.db'
git_repo='/home/jack/PLT-User'
case_folder='./PLT-User/src/com/domain/test/qray/cases/plt/usermanagement'
svn_username='jzheng'
svn_pwd='niP8Sf'
svn_addr='https://svn.domain.com/repos/V4/branches/offshore/t2/qraywriter'
svn_src='C:/Users/i306454/qray repo/src/com/domain/test/qray/cases'
svn_prefix='C:/Users/i306454/qray repo'
